version: '3.7'
services:
  dev-proxy:
    image: ghcr.io/navikt/poao-dev-proxy/poao-dev-proxy:2022.02.15_16.48-3a2864beb7dd
    container_name: poao-dev-proxy
    ports:
      - '58080:8080'
    environment:
      JSON_CONFIG: >
        {
          "proxies": [
            {
              "fromPath": "/deltakeroversikt/amt-tiltak",
              "toUrl": "https://amt.intern.dev.nav.no/deltakeroversikt/amt-tiltak",
              "preserveFromPath": false
            }
          ]
        }
