version: '3.7'
services:
  dev-proxy:
    image: ghcr.io/navikt/poao-dev-proxy/poao-dev-proxy:2022.01.24_16.17-8630e48a744f
    container_name: poao-dev-proxy
    ports:
      - '58080:8080'
    environment:
      JSON_CONFIG: >
        {
          "proxies": [
            { "fromPath": "/amt-tiltak", "toUrl": "https://amt-tiltaksarrangor-flate.dev.intern.nav.no", "preserveFromPath": true }
          ]
        }