apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: amt-tiltaksarrangor-flate
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/pto-frontend/pto-frontend:43fdd666f3a803f284da73b51e248c91b2760a3d
  port: 8080
  ingresses:
    - https://amt-tiltaksarrangor-flate.dev.intern.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  gcp:
    buckets:
      - name: amt-tiltaksarrangor-flate-dev
        cascadingDelete: false
  env:
    - name: GCS_BUCKET_NAME
      value: amt-tiltaksarrangor-flate-dev
    - name: CORS_DOMAIN
      value: "*"
