packages:
  - "."

allowBuilds:
  '@swc/core': false
  esbuild: true
  msw: true
  protobufjs: false
  cypress: true
  '@parcel/watcher': false

# Pakker må være 7 dager gamle før de kan installeres (likt som dependabot cooldown)
# Et sikkerhetstiltak i tilfelle en pakke blir komprimittert
minimumReleaseAge: 10080 # 24 x 60 x 7
