apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: amt-tiltaksarrangor-flate
  namespace: amt
  labels:
    team: amt
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2022.02.02_15.00-1cb75dc2fe84
  port: 8080
  ingresses:
    - https://www.nav.no/tiltaksarrangor/deltakeroversikt
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  idporten:
    enabled: true
    postLogoutRedirectURIs:
      - https://www.nav.no/tiltaksarrangor/deltakeroversikt
    sidecar:
      enabled: true
  tokenx:
    enabled: true
  gcp:
    buckets:
      - name: amt-tiltaksarrangor-flate-prod
  accessPolicy:
    outbound:
      rules:
        - application: amt-tiltak
  env:
    - name: JSON_CONFIG
      value: >
        {
          "contextPath": "/tiltaksarrangor/deltakeroversikt",
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "gcs": {
            "bucketName": "amt-tiltaksarrangor-flate-prod"
          },
          "auth": {
            "loginProvider": "ID_PORTEN"
          },
          "proxies": [
            {
              "fromPath": "/amt-tiltak", "toUrl": "http://amt-tiltak",
              "toApp": { "name": "amt-tiltak", "namespace": "amt", "cluster": "prod-gcp" }
            }
          ]
        }
