apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: amt-tiltaksarrangor-flate
  namespace: amt
  labels:
    team: amt
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2022.12.12_15.14-6d2623ef615d
  port: 8080
  ingresses:
    - https://amt.dev.nav.no/tiltaksarrangor/deltakeroversikt
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  idporten:
    enabled: true
    postLogoutRedirectURIs:
      - https://amt.dev.nav.no/tiltaksarrangor/deltakeroversikt
    sidecar:
      enabled: true
      autoLogin: true
  tokenx:
    enabled: true
  gcp:
    buckets:
      - name: amt-tiltaksarrangor-flate-dev
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: amt-tiltak
        - application: poao-unleash
          namespace: poao
          cluster: dev-gcp
  env:
    - name: JSON_CONFIG
      value: >
        {
          "contextPath": "/tiltaksarrangor/deltakeroversikt",
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "gcs": {
            "bucketName": "amt-tiltaksarrangor-flate-dev"
          },
          "auth": {
            "loginProvider": "ID_PORTEN"
          },
          "proxies": [
            {
              "fromPath": "/amt-tiltak", "toUrl": "http://amt-tiltak",
              "toApp": { "name": "amt-tiltak", "namespace": "amt", "cluster": "dev-gcp" }
            },
            {
              "fromPath": "/unleash",
              "toUrl": "http://poao-unleash.poao.svc.cluster.local",
              "preserveFromPath": false
            }
          ]
        }
