
export enum EndringType {
	LEGG_TIL_OPPSTARTSDATO = 'LEGG_TIL_OPPSTARTSDATO',
	ENDRE_OPPSTARTSDATO = 'ENDRE_OPPSTARTSDATO',
	FORLENG_DELTAKELSE = 'FORLENG_DELTAKELSE',
	AVSLUTT_DELTAKELSE = 'AVSLUTT_DELTAKELSE',
	DELTAKER_IKKE_AKTUELL = 'DELTAKER_IKKE_AKTUELL',
	ENDRE_PROSENT_DELTAKELSE = 'ENDRE_PROSENT_DELTAKELSE'
}
