name: Cypress test
on:
  pull_request:
    branches:
      - main
env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  cypress:
    name: Cypress test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
        with:
          version: 11.8.0
      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: '24'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
      - name: Cypress binary cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v5
        id: cypress-cache
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Install cypress binary
        if: steps.cypress-cache.outputs.cache-hit != 'true'
        run: pnpm exec cypress install
      - name: Check if PR is not created by Dependabot
        run: echo "IS_NOT_DEPENDABOT=${{ github.event.pull_request.user.login != 'dependabot[bot]' }}" >> $GITHUB_ENV
      - name: Run tests
        uses: cypress-io/github-action@fa4a118725a8f001170d49631ea89e5d66fee626 # v7.4.1
        with:
          browser: chrome
          start: pnpm start
          wait-on: sleep 5
          record: ${{ env.IS_NOT_DEPENDABOT }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
