name: Cypress cache
on:
  push:
    branches:
      - main

jobs:
  cypress-cache:
    name: Cypress cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        with:
          version: 11.8.0
      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: '24'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
      - name: Cypress binary cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v5
        id: cypress-cache
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install cypress binary
        if: steps.cypress-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile && pnpm exec cypress install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
