name: Cypress test
on:
  pull_request:
    branches:
      - main
env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  cypress:
    name: Cypress test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6
        with:
          version: 11.8.0
      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '24'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
      - name: Cypress binary cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v5
        id: cypress-cache
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Install cypress binary
        if: steps.cypress-cache.outputs.cache-hit != 'true'
        run: pnpm exec cypress install
      - name: Check if PR is not created by Dependabot
        run: echo "IS_NOT_DEPENDABOT=${{ github.event.pull_request.user.login != 'dependabot[bot]' }}" >> $GITHUB_ENV
      - name: Run tests
        uses: cypress-io/github-action@948d67d3074f1bbb6379c8bdbb04e95d2f8e593f # v7.4.0
        with:
          browser: chrome
          start: pnpm start
          wait-on: sleep 5
          record: ${{ env.IS_NOT_DEPENDABOT }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
