name: Deploy poao-frontend to dev
on:
  workflow_dispatch: # This workflow can be triggered manually from: https://github.com/navikt/amt-tiltaksarrangor-flate/actions/workflows/deploy-poao-frontend-dev.yaml
  push:
    paths:
      - ".nais/nais-dev.yaml"

jobs:
  deploy-dev:
    name: Deploy poao-frontend to dev
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Deploy application
        uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev.yaml 
          PRINT_PAYLOAD: true
