name: Deploy poao-frontend to dev
on:
  push:
    paths:
      - ".nais/nais-dev.yaml"

jobs:
  deploy-dev:
    name: Deploy poao-frontend to dev
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev.yaml 
          PRINT_PAYLOAD: true
