name: Deploy poao-frontend to prod
on:
  push:
    paths:
      - ".nais/nais-prod.yaml"

jobs:
  deploy-prod:
    name: Deploy poao-frontend to prod
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Deploy application
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais-prod.yaml 
          PRINT_PAYLOAD: true
