name: Deploy poao-frontend to prod
on:
  push:
    paths:
      - ".nais/nais-prod.yaml"

jobs:
  deploy-prod:
    name: Deploy poao-frontend to prod
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais-prod.yaml 
          PRINT_PAYLOAD: true
