name: Deploy poao-frontend to dev
on:
  workflow_dispatch: # This workflow can be triggered manually from: https://github.com/navikt/amt-tiltaksarrangor-flate/actions/workflows/deploy-poao-frontend-dev.yaml
  push:
    paths:
      - ".nais/nais-dev.yaml"

jobs:
  deploy-dev:
    name: Deploy poao-frontend to dev
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Deploy application
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev.yaml 
          PRINT_PAYLOAD: true
