name: Deploy poao-frontend to prod
on:
  push:
    paths:
      - ".nais/nais-prod.yaml"

jobs:
  deploy-prod:
    name: Deploy poao-frontend to prod
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Deploy application
        uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais-prod.yaml 
          PRINT_PAYLOAD: true
