name: Deploy poao-frontend to dev
on:
  push:
    paths:
      - ".nais/nais-dev.yaml"

jobs:
  deploy-dev:
    name: Deploy poao-frontend to dev
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev.yaml 
          PRINT_PAYLOAD: true
