name: Deploy application
on:
  workflow_dispatch: # This workflow can be triggered manually from: https://github.com/navikt/amt-tiltaksarrangor-flate/actions/workflows/deploy.yaml
  push:
    branches:
      - main
env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  test-and-build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.6.2
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Run tests
        run: pnpm test
      - name: Build application
        run: pnpm build
      - name: Upload frontend asset files
        uses: actions/upload-artifact@v4
        with:
          name: frontend-assets
          path: build
          retention-days: 1

  deploy-dev:
    name: Deploy application to dev
    runs-on: ubuntu-latest
    needs: test-and-build
    permissions:
      id-token: 'write' # Used to authenticate with Google Cloud
      contents: 'write' # Create release
    steps:
      - name: Download frontend asset files
        uses: actions/download-artifact@v4
        with:
          name: frontend-assets
          path: build
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/696882554390/locations/global/workloadIdentityPools/github/providers/github-action
          service_account: amt-tiltaksarrangor-flate-gcs@amt-dev-d98f.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Upload files to GCS
        run: gsutil -m rsync -r build gs://amt-tiltaksarrangor-flate-dev
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Release to dev
          tag_name: release/dev@${{ github.sha }}
          prerelease: true

  deploy-prod:
    name: Deploy application to prod
    runs-on: ubuntu-latest
    needs: deploy-dev
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: 'write' # Used to authenticate with Google Cloud
      contents: 'write' # Create release
    steps:
      - name: Download frontend asset files
        uses: actions/download-artifact@v4
        with:
          name: frontend-assets
          path: build
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/337368476147/locations/global/workloadIdentityPools/github/providers/github-action
          service_account: amt-tiltaksarrangor-flate-gcs@amt-prod-d4dd.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Upload files to GCS
        run: gsutil -m rsync -r build gs://amt-tiltaksarrangor-flate-prod
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Release to prod
          tag_name: release/prod@${{ github.sha }}
          prerelease: false
