name: Lint & tests
on:
  push:
    branches-ignore:
      - main
env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  lint-and-test:
    name: Lint & run tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.13.4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Run tests
        run: pnpm test
