name: Lint & tests
on:
  push:
    branches-ignore:
      - main
env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  lint-and-test:
    name: Lint & run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: npm run test
