name: Opprett lenke til test applikasjon for PR
on:
  pull_request:
    branches:
      - main
    types:
      - opened
jobs:
  create-link-to-app:
    if: github.event.pull_request.head.repo.fork != true && github.event.pull_request.user.login != 'dependabot[bot]'
    permissions:
      pull-requests: "write"
    name: Opprett lenke til test applikasjon for PR
    runs-on: ubuntu-latest
    steps:
      - name: Opprett lenke til test applikasjon for PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            URL for testing: https://amt.intern.dev.nav.no/deltakeroversikt/pr-${{ github.event.number }}/index.html
