name: Deploy Pull Request Branch
on:
  pull_request:
    branches:
      - main
env:
  CI: true
  TZ: Europe/Oslo

jobs:
  deploy-pull-request-branch:
    if: github.event.pull_request.head.repo.fork != true && github.event.pull_request.user.login != 'dependabot[bot]'
    name: Deploy Pull Request Branch
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write' # Used to authenticate with Google Cloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Build Pull Request Application
        run: NODE_ENV=development VITE_MOCK_REQUEST_HANDLER=PULL_REQUEST BASE=/deltakeroversikt/pr-${{ github.event.number }}/ pnpm build
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/696882554390/locations/global/workloadIdentityPools/github/providers/github-action
          service_account: amt-tiltaksarrangor-flate-gcs@amt-dev-d98f.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Upload files to GCS
        run: gsutil -m rsync -r build gs://amt-tiltaksarrangor-flate-dev/pr-${{ github.event.number }}
