name: Deploy Pull Request Branch
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
env:
  CI: true
  TZ: Europe/Oslo

jobs:
  deploy-pull-request-branch:
    name: Deploy Pull Request Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build Pull Request Application
        run: VITE_MOCK_REQUEST_HANDLER=PULL_REQUEST BASE=/tiltaksarrangor/deltakeroversikt/pr-${{ github.event.number }}/ npm run build
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCS_SA_KEY_DEV }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Upload files to GCS
        run: gsutil -m rsync -r build gs://amt-tiltaksarrangor-flate-dev/pr-${{ github.event.number }}
