name: Deploy Pull Request Branch
on:
  workflow_dispatch: # This workflow can be triggered manually from: https://github.com/navikt/amt-tiltaksarrangor-flate/actions/workflows/deploy.yaml
  pull_request:
    branches:
      - main
env:
  CI: true
  TZ: Europe/Oslo

jobs:
  deploy-pull-request-branch:
    if: github.event.pull_request.head.repo.fork != true
    name: Deploy Pull Request Branch
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write' # Used to authenticate with Google Cloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Build Pull Request Application
        run: BASE=/deltakeroversikt/pr-${{ github.event.number }}/ pnpm build --mode pull-request
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/696882554390/locations/global/workloadIdentityPools/github/providers/github-action
          service_account: amt-tiltaksarrangor-flate-gcs@amt-dev-d98f.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Upload files to GCS
        run: gsutil -m rsync -r build gs://amt-tiltaksarrangor-flate-dev/pr-${{ github.event.number }}
  create-link-to-app:
    if: github.event.pull_request.head.repo.fork != true && github.event_name == 'pull_request' && github.event.action == 'opened'
    needs: deploy-pull-request-branch
    permissions:
      pull-requests: "write"
    name: Opprett lenke til test applikasjon for PR
    runs-on: ubuntu-latest
    steps:
      - name: Opprett lenke til test applikasjon for PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            URL for testing: https://amt.intern.dev.nav.no/deltakeroversikt/pr-${{ github.event.number }}/index.html and https://amt.ansatt.dev.nav.no/deltakeroversikt/pr-${{ github.event.number }}/index.html
